server:
  port: 8082
  shutdown: graceful
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: gateway
    # config gateway routers https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-loadbalancerclient-filter
  cloud:
    gateway:
      routes:
        #- config route id
        - id: payment-morning-service
          #- config route uri with loadbalancer
          uri: lb://payment-morning
          predicates:
            #- config predicates route uri with loadbalancer path
            - Path=/payment-morning/**
          filters:
            - StripPrefix=1
        - id: payment-control-service
          uri: lb://payment-control
          predicates:
            - Path=/payment-control/**
          filters:
            - StripPrefix=1
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service

